# RPA+FH model for single charge sequence
# Short-range interaction contributes to only the k=0 FH term
# The FH term ehs parameters follow the definition in the PRL paper

# ver Git.1 Apr 14, 2020
# Upload to github

# Jan 1, 2019
# - Add function for pH-dependent charges

import numpy as np

R_pKa = 12.10
H_pKa = 6.04
K_pKa = 10.67
D_pKa = 3.71
E_pKa = 4.15

def qi_calc(x):
    return 10**x/(1+10**x)

def get_the_charge(seqname, pH=None):
    the_seq = getattr(polymers, seqname)
    N = len(the_seq)
    sigmai = np.zeros(N)

    use_pKa = False if pH == None else True
     

    for i in range(0, N):
        if the_seq[i] == 'D' :
            sigmai[i] = -qi_calc(pH-D_pKa) if use_pKa else -1
        elif the_seq[i] == 'E' :
            sigmai[i] = -qi_calc(pH-E_pKa) if use_pKa else -1
        elif the_seq[i] == 'R' :
            sigmai[i] = qi_calc(R_pKa-pH) if use_pKa else 1
        elif the_seq[i] == 'K' :
            sigmai[i] = qi_calc(K_pKa-pH) if use_pKa else 1
        elif the_seq[i] == 'H' :
            sigmai[i] = qi_calc(H_pKa-pH) if use_pKa else 0 
            if 'pH1' in seqname:
                print('seq is pH1')
                sigmai[i] = 1     
        else:
            sigmai[i] = 0

    return sigmai, N, the_seq




class polymers:

    EB1_WT = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNKPK" + "KPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPKAGPGVV" + "RKNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_DE4Q = \
    "Q" + "GKQYQPVAAR" + "QGQQTAVAPS" + "LVAPALNKPK" + "KPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPKAGPGVV" + "RKNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_KR6Q = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNQPQ" + "QPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPQAGPGVV" + "QQNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"
    
    EB1_Reverse = \
    "GNGVGPNKRV" + "VGPGAKPAAA" + "TRQTSIPRQP" + "AASSSTLPKK" +\
    "PKNLAPAVLS" + "PAVATEQGQR" + "AAVPDYDKGD"+ "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"


    EB1_KR5Q = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNQPQ" + "QPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPKAGPGVV" + "QQNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_KR4Q = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNQPQ" + "QPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPQAGPGVV" + "RKNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_KR3Q = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNQPQ" + "QPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPKAGPGVV" + "RKNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_KR12Q = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNKPK" + "KPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPQAGPGVV" + "QQNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_KR2Q = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNKPK" + "KPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPKAGPGVV" + "QQNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"
    
    EB1_KR1Q = \
    "D" + "GKDYDPVAAR" + "QGQETAVAPS" + "LVAPALNKPK" + "KPLTSSSAAP" +\
    "QRPISTQRTA" + "AAPQAGPGVV" + "RKNPGVGNG" + "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +\
    "TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_KR = \
    "DGDYDPVAAQKRGQETAVAPSLKKVAPALNPPLTKRSSSAAPQPISRKTQTAAAPAGPRKGVVNPGVGNG"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
    EB1_3KR = \
    "DGDYDPVAAQGQKRKETAVAPSLVAPAKKRLNPPLTSSSAAPRKRQPISTQTAAAPAKGPGVVNPGVGNG"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
    EB1_5KR = \
    "DGDYDPVAAQGQETAVAPSLKRKKKVAPALNPPLTSSSAAPQPISRRKRKTQTAAAPAGPGVVNPGVGNG"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
    
    EB1_10KR = \
    "DGDYDPVAAQGQETAVAPSLVAPALNPPLTKRKKKRRKRKSSSAAPQPISTQTAAAPAGPGVVNPGVGNG"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"


    EB1_dist10 = \
    "DGDYDPVAAQ" + "GQETAVAPSL" + "VAPALNPPLT" + "KRKKKRRKRK"+ "SSSAAP" +\
    "QPISTQTA" + "AAPAGPGVV" + "NPGVGNG" +\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
    
    EB1_dist5 = \
    "DGDYDPVAAQ" + "GQETAVAPSL" + "KRKKK"+"VAPALNPPLT" +"SSSAAP" +\
    "QPIS" + "RRKRK"+ "TQTAAAPAGP" + "GVVNPGVGNG" +\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_dist32 = \
    "DGDYDPVAAQGQ" + "KR"+ "ETAVAPSLVAPA" + "KKK"+ "LNPPLTSSSAAP"+ "RR" +\
    "QPISTQTAAAPA"  + "KRK"+ "GPGVVNPGVGNG" +\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
    EB1_dist3= \
    "DGDYDPVAAQGQKRKETAVAPSLVAPAKKRLNPPLTSSSAAPRKRQPISTQTAAAPAKGPGVVNPGVGNG"  +\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
    EB1_dist2= \
    "DGDYDPVAAQKRGQETAVAPSLKKVAPALNPPLTKRSSSAAPQPISRKTQTAAAPAGPRKGVVNPGVGNG"  +\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
    EB1_Average = \
    "DGDYDKPVAAQRGQETAKVAPSLKVAPALKNPPLTRSSSAAPRQPISTQKTAAAPARGPGVVNKPGVGNG"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    
    EB1_scr1 = \
    "PGSGAVPLGRKRYAPAVGGARSELASAPTIPAAPRQNLPSQVPPQKVKKVGNTAQDTGSADNVAKKTPAD"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"
   
    EB1_scr2 = \
    "PPAEPPIGPQYPNGGPAVSAGSDPGKSVPTAQAASRTQQGSTALAKNAKLVLARTKVVPRVNDAGDRKAK"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_scr3 = \
    "AVLADQTQVNRADANAAIQKPGPVKGVYALLKRGAPNRSTQPVRAGPPPKDKGTSSVSAAPKGSTAGEPP"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_scr4 = \
    "VDDAYGAPRAQSPQKRPDGGPPANAGAVKSLKNSAETPTALAGKSNVPAVKQKRITTQRSPPGPLVAGAV"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_scr5 = \
    "DAPIQLPPGSVSDSKVVAPGTASEAVTDGYAATNKAKKQQKAAPPPKRGNLGPPVALRQRNSRAAVGTGP"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_scr6 = \
    "PPKARAVIAPDLVSGTRNTPSDQAGVSPGEAGPRNGVVARAYQPDKVLKAANQTSQLPGPKGSTAKKAPA"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_scr7 = \
    "TVKAGVLKVQPTANVPGQAAPRLTRGPAKSGKLANDSASEYRSQPPAVQPAPARGPDISPKGDTKVGAAN"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_scr8 = \
    "VGVPRTNNAPPGQAGAGVGGASKRDPASKPPETLIKLKSQPRTYAARAKAPGQDATKVSADNPLQPSVVA"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"

    EB1_scr9 = \
    "DAATPPQLGVASIKDAPPRPSGLKVSVNTVAERAGQAGDLYAPKRNAQNVKPSPPKGAGRQTAPAGTVKS"+\
    "QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ" +"TDEGFVIPDE" + "GGPQEEQEEY"


